[build]
  # Build the frontend and output to the dist directory.  Netlify
  # automatically installs dependencies using npm, so no need to run pnpm.
  command = "npm run build"
  publish ="dist" 
[[redirects]]
  
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    # Content security policy allows our own domain and the CDNs used for React, Chart.js and html2pdf.js
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://unpkg.com https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'"

[context.production.environment]
  ALPHAVANTAGE_API_KEY = ""
  POLYGON_API_KEY = ""
  FMP_API_KEY = ""

# Configure Netlify Functions.  The directory is set at the top of the build
# block and here we schedule our refreshEarnings function to run once per day.
[functions]
  directory = "netlify/functions"

[functions.refreshEarnings]
  schedule = "@daily"
