[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    # Content security policy allows our own domain and the CDNs used for React, Chart.js and html2pdf.js
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://unpkg.com https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'"

[context.production.environment]
  ALPHAVANTAGE_API_KEY = ""
  POLYGON_API_KEY = ""
  FMP_API_KEY = ""

[[functions]]
  name = "refreshEarnings"
  schedule = "@daily"
